const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./endpoints.js']

const doc = {
    info: getInfo(),
    host: getHost(),
    basePath: getBasePath(),
    schemes: getSchemes(),
    consumes: getApplicationType(),
    produces: getApplicationType(),
    tags: getTags(),
    securityDefinitions: getSecurityDefinitions(),
    definitions: getDefinitions()
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})

function getInfo() {
    return {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    };
}

function getHost() {
    return "localhost:3000";
}

function getBasePath() {
    return "/";
}

function getSchemes() {
    return ['http', 'https'];
}

function getApplicationType() {
    return ['application/json'];
}

function getTags() {
    return [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ];
}

function getSecurityDefinitions() {
    return {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    };
}

// se utilizarmos o $ como param, podemos observar que na documentação
// ele sera required.
function getDefinitions() {
    return {
        User: {
            name: "Jhon Doe",
            age: 29,
            parents: {
                father: "Simon Doe",
                mother: "Marie Doe"
            },
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            about: ""
        }
    };
}